version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tr3mor"
    assignees:
      - "tr3mor"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
