name: testing
on:
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Install X11 dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=colored-line-number
      - name: Test
        run: go test -v ./...
